<?php
function iied_migrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

// Get the parent menu id
/*
function get_menu_plid($path) {

	$p = explode('/',$path);
	$url = '';
	
	
	for ($i = 0; $i<(count($p) - 1); $i++) {
		$url .= ($i == 0 ) ? $p[$i] : '/' . $p[$i];
	}
	
	$result = db_select('menu_links', 'mlid')
    ->fields('mlid')
    ->condition('link_path', drupal_get_normal_path($url))
    ->execute()
    ->fetchAssoc();
	
	return $result['mlid'];
}
*/